# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_odrive/odrive_ctrl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class odrive_ctrl(genpy.Message):
  _md5sum = "11157a5f66bebeef0ff837893ae31cd8"
  _type = "ros_odrive/odrive_ctrl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#Header header    # ROS Message headaer

int8 target     # target

int32 command   # Command ID
uint8 axis      # Axis number
float32 fval    # Float value 
float32 fval2   # Float second value (in case of dual axis command)

"""
  __slots__ = ['target','command','axis','fval','fval2']
  _slot_types = ['int8','int32','uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target,command,axis,fval,fval2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(odrive_ctrl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target is None:
        self.target = 0
      if self.command is None:
        self.command = 0
      if self.axis is None:
        self.axis = 0
      if self.fval is None:
        self.fval = 0.
      if self.fval2 is None:
        self.fval2 = 0.
    else:
      self.target = 0
      self.command = 0
      self.axis = 0
      self.fval = 0.
      self.fval2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_biB2f().pack(_x.target, _x.command, _x.axis, _x.fval, _x.fval2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.target, _x.command, _x.axis, _x.fval, _x.fval2,) = _get_struct_biB2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_biB2f().pack(_x.target, _x.command, _x.axis, _x.fval, _x.fval2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.target, _x.command, _x.axis, _x.fval, _x.fval2,) = _get_struct_biB2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_biB2f = None
def _get_struct_biB2f():
    global _struct_biB2f
    if _struct_biB2f is None:
        _struct_biB2f = struct.Struct("<biB2f")
    return _struct_biB2f
