(cl:in-package ros_odrive-msg)
(cl:export '(TARGET-VAL
          TARGET
          VBUS-VAL
          VBUS
          ERROR0-VAL
          ERROR0
          STATE0-VAL
          STATE0
          VEL0-VAL
          VEL0
          POS0-VAL
          POS0
          CURR0B-VAL
          CURR0B
          CURR0C-VAL
          CURR0C
          TEMP0-VAL
          TEMP0
          ERROR1-VAL
          ERROR1
          STATE1-VAL
          STATE1
          VEL1-VAL
          VEL1
          POS1-VAL
          POS1
          CURR1B-VAL
          CURR1B
          CURR1C-VAL
          CURR1C
          TEMP1-VAL
          TEMP1
))